# Generated by Django 5.2.3 on 2025-07-01 07:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="FileUpload/")),
            ],
        ),
        migrations.CreateModel(
            name="LoadCategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("commercial", "Commercial"),
                            ("agricultural", "Agricultural"),
                            ("industrial", "Industrial"),
                            ("residential", "Residential"),
                            ("public", "Public"),
                            ("others", "Others"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "categoryFile",
                    models.CharField(blank=True, default="", max_length=400, null=True),
                ),
                ("salesCAGR", models.IntegerField(blank=True, default=0, null=True)),
                ("specifySplit", models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(default="", max_length=50)),
                (
                    "status",
                    models.CharField(blank=True, default="", max_length=20, null=True),
                ),
                ("errorLog", models.TextField()),
                ("time", models.FloatField(blank=True, default=0.0, null=True)),
            ],
            options={
                "verbose_name_plural": "User Analyses Log",
            },
        ),
        migrations.CreateModel(
            name="VehicleCategoryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicleCategory",
                    models.CharField(
                        choices=[
                            ("car", "Car"),
                            ("bus", "Bus"),
                            ("2-wheeler", "2-Wheeler"),
                            ("3-wheeler", "3-Wheeler"),
                            ("others", "Others"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("n", models.IntegerField(blank=True, default=0, null=True)),
                ("f", models.IntegerField(blank=True, default=0, null=True)),
                ("c", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "p",
                    models.FloatField(
                        blank=True,
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("e", models.FloatField(blank=True, default=0.0, null=True)),
                ("r", models.IntegerField(blank=True, default=0, null=True)),
                ("k", models.IntegerField(blank=True, default=0, null=True)),
                ("l", models.IntegerField(blank=True, default=0, null=True)),
                ("g", models.IntegerField(blank=True, default=0, null=True)),
                ("h", models.IntegerField(blank=True, default=0, null=True)),
                ("s", models.IntegerField(blank=True, default=0, null=True)),
                ("u", models.IntegerField(blank=True, default=0, null=True)),
                ("rowlimit_xl", models.IntegerField(default=2000000)),
                ("CAGR_V", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "baseElectricityTariff",
                    models.FloatField(
                        blank=True,
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.CharField(default="Not assigned", max_length=255),
                ),
                (
                    "invitation_status",
                    models.CharField(default="Pending", max_length=50),
                ),
                ("invitation_username", models.CharField(blank=True, max_length=255)),
                ("temporary_password", models.CharField(blank=True, max_length=255)),
                (
                    "invitation_token",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loadCategory",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "isLoadSplit",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "isLoadSplitFile",
                    models.CharField(blank=True, default="", max_length=400, null=True),
                ),
                ("category_data", models.JSONField(default=list)),
                (
                    "numOfvehicleCategory",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("vehicle_category_data", models.JSONField(default=list)),
                (
                    "resolution",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("BR_F", models.CharField(blank=True, default="", max_length=10)),
                (
                    "shared_saving",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("sum_pk_cost", models.FloatField(blank=True, default=0, null=True)),
                ("sum_zero_cost", models.FloatField(blank=True, default=0, null=True)),
                ("sum_op_cost", models.FloatField(blank=True, default=0, null=True)),
                ("win_pk_cost", models.FloatField(blank=True, default=0, null=True)),
                ("win_zero_cost", models.FloatField(blank=True, default=0, null=True)),
                ("win_op_cost", models.FloatField(blank=True, default=0, null=True)),
                ("summer_date", models.JSONField(default=list)),
                ("winter_date", models.JSONField(default=list)),
                ("s_pks", models.CharField(default="", max_length=10)),
                ("s_pke", models.CharField(default="", max_length=10)),
                (
                    "s_sx",
                    models.FloatField(
                        blank=True,
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("s_ops", models.CharField(default="", max_length=10)),
                ("s_ope", models.CharField(default="", max_length=10)),
                (
                    "s_rb",
                    models.FloatField(
                        blank=True,
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("w_pks", models.CharField(default="00:00", max_length=10)),
                ("w_pke", models.CharField(default="00:00", max_length=10)),
                (
                    "w_sx",
                    models.FloatField(
                        blank=True,
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("w_ops", models.CharField(default="00:00", max_length=10)),
                ("w_ope", models.CharField(default="00:00", max_length=10)),
                (
                    "w_rb",
                    models.FloatField(
                        blank=True,
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("date1_start", models.CharField(default="", max_length=10)),
                ("date1_end", models.CharField(default="", max_length=10)),
                ("date2_start", models.CharField(default="", max_length=10)),
                ("date2_end", models.CharField(default="", max_length=10)),
                ("fileId", models.IntegerField(default=0)),
                ("user_name", models.CharField(default="", max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loadCategory1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="load_cat_1",
                        to="elevate.loadcategorymodel",
                    ),
                ),
                (
                    "loadCategory2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="load_cat_2",
                        to="elevate.loadcategorymodel",
                    ),
                ),
                (
                    "loadCategory3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="load_cat_3",
                        to="elevate.loadcategorymodel",
                    ),
                ),
                (
                    "loadCategory4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="load_cat_4",
                        to="elevate.loadcategorymodel",
                    ),
                ),
                (
                    "loadCategory5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="load_cat_5",
                        to="elevate.loadcategorymodel",
                    ),
                ),
                (
                    "loadCategory6",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="load_cat_6",
                        to="elevate.loadcategorymodel",
                    ),
                ),
                (
                    "vehicleCategoryData1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_cat_1",
                        to="elevate.vehiclecategorymodel",
                    ),
                ),
                (
                    "vehicleCategoryData2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_cat_2",
                        to="elevate.vehiclecategorymodel",
                    ),
                ),
                (
                    "vehicleCategoryData3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_cat_3",
                        to="elevate.vehiclecategorymodel",
                    ),
                ),
                (
                    "vehicleCategoryData4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_cat_4",
                        to="elevate.vehiclecategorymodel",
                    ),
                ),
                (
                    "vehicleCategoryData5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicle_cat_5",
                        to="elevate.vehiclecategorymodel",
                    ),
                ),
            ],
        ),
    ]
