# Generated by Django 5.2.3 on 2025-07-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
