# Generated by Django 5.2.3 on 2025-07-01 12:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevate", "0002_userprofile_password_reset_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PermanentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "loadCategory",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "isLoadSplit",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "isLoadSplitFile",
                    models.CharField(blank=True, default="", max_length=400, null=True),
                ),
                ("category_data", models.JSONField(default=list)),
                (
                    "numOfvehicleCategory",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "resolution",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("BR_F", models.CharField(blank=True, default="", max_length=10)),
                (
                    "shared_saving",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("sum_pk_cost", models.FloatField(blank=True, default=0, null=True)),
                ("sum_zero_cost", models.FloatField(blank=True, default=0, null=True)),
                ("sum_op_cost", models.FloatField(blank=True, default=0, null=True)),
                ("win_pk_cost", models.FloatField(blank=True, default=0, null=True)),
                ("win_zero_cost", models.FloatField(blank=True, default=0, null=True)),
                ("win_op_cost", models.FloatField(blank=True, default=0, null=True)),
                ("summer_date", models.JSONField(default=list)),
                ("winter_date", models.JSONField(default=list)),
                ("s_pks", models.CharField(default="", max_length=10)),
                ("s_pke", models.CharField(default="", max_length=10)),
                (
                    "s_sx",
                    models.FloatField(
                        blank=True,
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("s_ops", models.CharField(default="", max_length=10)),
                ("s_ope", models.CharField(default="", max_length=10)),
                (
                    "s_rb",
                    models.FloatField(
                        blank=True,
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("w_pks", models.CharField(default="00:00", max_length=10)),
                ("w_pke", models.CharField(default="00:00", max_length=10)),
                (
                    "w_sx",
                    models.FloatField(
                        blank=True,
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("w_ops", models.CharField(default="00:00", max_length=10)),
                ("w_ope", models.CharField(default="00:00", max_length=10)),
                (
                    "w_rb",
                    models.FloatField(
                        blank=True,
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("date1_start", models.CharField(default="", max_length=10)),
                ("date1_end", models.CharField(default="", max_length=10)),
                ("date2_start", models.CharField(default="", max_length=10)),
                ("date2_end", models.CharField(default="", max_length=10)),
                ("user_name", models.CharField(default="", max_length=50)),
                (
                    "loadCategory1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permanent_load_cat_1",
                        to="elevate.loadcategorymodel",
                    ),
                ),
                (
                    "loadCategory2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permanent_load_cat_2",
                        to="elevate.loadcategorymodel",
                    ),
                ),
                (
                    "loadCategory3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permanent_load_cat_3",
                        to="elevate.loadcategorymodel",
                    ),
                ),
                (
                    "loadCategory4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permanent_load_cat_4",
                        to="elevate.loadcategorymodel",
                    ),
                ),
                (
                    "loadCategory5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permanent_load_cat_5",
                        to="elevate.loadcategorymodel",
                    ),
                ),
                (
                    "loadCategory6",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permanent_load_cat_6",
                        to="elevate.loadcategorymodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permanent_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicleCategoryData1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permanent_vehicle_cat_1",
                        to="elevate.vehiclecategorymodel",
                    ),
                ),
                (
                    "vehicleCategoryData2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permanent_vehicle_cat_2",
                        to="elevate.vehiclecategorymodel",
                    ),
                ),
                (
                    "vehicleCategoryData3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permanent_vehicle_cat_3",
                        to="elevate.vehiclecategorymodel",
                    ),
                ),
                (
                    "vehicleCategoryData4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permanent_vehicle_cat_4",
                        to="elevate.vehiclecategorymodel",
                    ),
                ),
                (
                    "vehicleCategoryData5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permanent_vehicle_cat_5",
                        to="elevate.vehiclecategorymodel",
                    ),
                ),
            ],
        ),
    ]
