# Generated by Django 5.2.3 on 2025-07-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevate", "0004_alter_permanentanalysis_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="permanentanalysis",
            name="vehicle_category_data",
            field=models.JSONField(default=list),
        ),
    ]
