# Generated by Django 5.2.3 on 2025-07-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevate", "0005_permanentanalysis_vehicle_category_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(default="user", max_length=50),
        ),
    ]
