# Generated by Django 5.2.3 on 2025-07-07 05:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevate", "0006_userprofile_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysis",
            options={"verbose_name": "analysis", "verbose_name_plural": "analyses"},
        ),
        migrations.AlterModelOptions(
            name="files",
            options={"verbose_name": "file", "verbose_name_plural": "files"},
        ),
        migrations.AlterModelOptions(
            name="loadcategorymodel",
            options={
                "verbose_name": "load category",
                "verbose_name_plural": "load categories",
            },
        ),
        migrations.AlterModelOptions(
            name="permanentanalysis",
            options={
                "verbose_name": "permanent analysis",
                "verbose_name_plural": "permanent analyses",
            },
        ),
        migrations.AlterModelOptions(
            name="useranalysis",
            options={
                "verbose_name": "user analysis log",
                "verbose_name_plural": "user analyses log",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="vehiclecategorymodel",
            options={
                "verbose_name": "vehicle category",
                "verbose_name_plural": "vehicle categories",
            },
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="BR_F",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="fileId",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="isLoadSplit",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="isLoadSplitFile",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="loadCategory",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="loadCategory1",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="loadCategory2",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="loadCategory3",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="loadCategory4",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="loadCategory5",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="loadCategory6",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="numOfvehicleCategory",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="s_ope",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="s_ops",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="s_pke",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="s_pks",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="s_rb",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="s_sx",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="sum_op_cost",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="sum_pk_cost",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="sum_zero_cost",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="vehicleCategoryData1",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="vehicleCategoryData2",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="vehicleCategoryData3",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="vehicleCategoryData4",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="vehicleCategoryData5",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="w_ope",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="w_ops",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="w_pke",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="w_pks",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="w_rb",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="w_sx",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="win_op_cost",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="win_pk_cost",
        ),
        migrations.RemoveField(
            model_name="analysis",
            name="win_zero_cost",
        ),
        migrations.RemoveField(
            model_name="loadcategorymodel",
            name="categoryFile",
        ),
        migrations.RemoveField(
            model_name="loadcategorymodel",
            name="salesCAGR",
        ),
        migrations.RemoveField(
            model_name="loadcategorymodel",
            name="specifySplit",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="BR_F",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="isLoadSplit",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="isLoadSplitFile",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="loadCategory",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="loadCategory1",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="loadCategory2",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="loadCategory3",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="loadCategory4",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="loadCategory5",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="loadCategory6",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="numOfvehicleCategory",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="s_ope",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="s_ops",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="s_pke",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="s_pks",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="s_rb",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="s_sx",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="sum_op_cost",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="sum_pk_cost",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="sum_zero_cost",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="vehicleCategoryData1",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="vehicleCategoryData2",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="vehicleCategoryData3",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="vehicleCategoryData4",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="vehicleCategoryData5",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="w_ope",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="w_ops",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="w_pke",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="w_pks",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="w_rb",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="w_sx",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="win_op_cost",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="win_pk_cost",
        ),
        migrations.RemoveField(
            model_name="permanentanalysis",
            name="win_zero_cost",
        ),
        migrations.RemoveField(
            model_name="useranalysis",
            name="errorLog",
        ),
        migrations.RemoveField(
            model_name="useranalysis",
            name="userName",
        ),
        migrations.RemoveField(
            model_name="vehiclecategorymodel",
            name="CAGR_V",
        ),
        migrations.RemoveField(
            model_name="vehiclecategorymodel",
            name="baseElectricityTariff",
        ),
        migrations.RemoveField(
            model_name="vehiclecategorymodel",
            name="c",
        ),
        migrations.RemoveField(
            model_name="vehiclecategorymodel",
            name="e",
        ),
        migrations.RemoveField(
            model_name="vehiclecategorymodel",
            name="f",
        ),
        migrations.RemoveField(
            model_name="vehiclecategorymodel",
            name="g",
        ),
        migrations.RemoveField(
            model_name="vehiclecategorymodel",
            name="h",
        ),
        migrations.RemoveField(
            model_name="vehiclecategorymodel",
            name="k",
        ),
        migrations.RemoveField(
            model_name="vehiclecategorymodel",
            name="l",
        ),
        migrations.RemoveField(
            model_name="vehiclecategorymodel",
            name="n",
        ),
        migrations.RemoveField(
            model_name="vehiclecategorymodel",
            name="p",
        ),
        migrations.RemoveField(
            model_name="vehiclecategorymodel",
            name="r",
        ),
        migrations.RemoveField(
            model_name="vehiclecategorymodel",
            name="rowlimit_xl",
        ),
        migrations.RemoveField(
            model_name="vehiclecategorymodel",
            name="s",
        ),
        migrations.RemoveField(
            model_name="vehiclecategorymodel",
            name="u",
        ),
        migrations.RemoveField(
            model_name="vehiclecategorymodel",
            name="vehicleCategory",
        ),
        migrations.AddField(
            model_name="analysis",
            name="file_id",
            field=models.PositiveIntegerField(default=0, verbose_name="file ID"),
        ),
        migrations.AddField(
            model_name="analysis",
            name="is_load_split",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")],
                default="",
                max_length=20,
                verbose_name="is load split",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="load_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_load_categories",
                to="elevate.loadcategorymodel",
                verbose_name="load categories",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="load_category_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="load category count",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="load_split_file",
            field=models.CharField(
                blank=True,
                default="",
                max_length=400,
                null=True,
                verbose_name="load split file",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="summer_op_cost",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="summer operating cost"
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="summer_op_end",
            field=models.CharField(
                default="", max_length=10, verbose_name="summer operating end"
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="summer_op_start",
            field=models.CharField(
                default="", max_length=10, verbose_name="summer operating start"
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="summer_peak_cost",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="summer peak cost"
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="summer_peak_end",
            field=models.CharField(
                default="", max_length=10, verbose_name="summer peak end"
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="summer_peak_start",
            field=models.CharField(
                default="", max_length=10, verbose_name="summer peak start"
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="summer_rb",
            field=models.FloatField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="summer rb",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="summer_sx",
            field=models.FloatField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="summer sx",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="summer_zero_cost",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="summer zero cost"
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="vehicle_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_vehicle_categories",
                to="elevate.vehiclecategorymodel",
                verbose_name="vehicle categories",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="vehicle_category_count",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="vehicle category count",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="winter_op_cost",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="winter operating cost"
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="winter_op_end",
            field=models.CharField(
                default="00:00", max_length=10, verbose_name="winter operating end"
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="winter_op_start",
            field=models.CharField(
                default="00:00", max_length=10, verbose_name="winter operating start"
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="winter_peak_cost",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="winter peak cost"
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="winter_peak_end",
            field=models.CharField(
                default="00:00", max_length=10, verbose_name="winter peak end"
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="winter_peak_start",
            field=models.CharField(
                default="00:00", max_length=10, verbose_name="winter peak start"
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="winter_rb",
            field=models.FloatField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="winter rb",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="winter_sx",
            field=models.FloatField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="winter sx",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="winter_zero_cost",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="winter zero cost"
            ),
        ),
        migrations.AddField(
            model_name="loadcategorymodel",
            name="category_file",
            field=models.CharField(
                blank=True,
                default="",
                max_length=400,
                null=True,
                verbose_name="category file",
            ),
        ),
        migrations.AddField(
            model_name="loadcategorymodel",
            name="sales_cagr",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="sales CAGR"
            ),
        ),
        migrations.AddField(
            model_name="loadcategorymodel",
            name="specify_split",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="specify split"
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="is_load_split",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")],
                default="",
                max_length=20,
                verbose_name="is load split",
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="load_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_load_categories",
                to="elevate.loadcategorymodel",
                verbose_name="load categories",
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="load_category_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="load category count",
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="load_split_file",
            field=models.CharField(
                blank=True,
                default="",
                max_length=400,
                null=True,
                verbose_name="load split file",
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="summer_op_cost",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="summer operating cost"
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="summer_op_end",
            field=models.CharField(
                default="", max_length=10, verbose_name="summer operating end"
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="summer_op_start",
            field=models.CharField(
                default="", max_length=10, verbose_name="summer operating start"
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="summer_peak_cost",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="summer peak cost"
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="summer_peak_end",
            field=models.CharField(
                default="", max_length=10, verbose_name="summer peak end"
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="summer_peak_start",
            field=models.CharField(
                default="", max_length=10, verbose_name="summer peak start"
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="summer_rb",
            field=models.FloatField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="summer rb",
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="summer_sx",
            field=models.FloatField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="summer sx",
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="summer_zero_cost",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="summer zero cost"
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="vehicle_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_vehicle_categories",
                to="elevate.vehiclecategorymodel",
                verbose_name="vehicle categories",
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="vehicle_category_count",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="vehicle category count",
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="winter_op_cost",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="winter operating cost"
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="winter_op_end",
            field=models.CharField(
                default="00:00", max_length=10, verbose_name="winter operating end"
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="winter_op_start",
            field=models.CharField(
                default="00:00", max_length=10, verbose_name="winter operating start"
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="winter_peak_cost",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="winter peak cost"
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="winter_peak_end",
            field=models.CharField(
                default="00:00", max_length=10, verbose_name="winter peak end"
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="winter_peak_start",
            field=models.CharField(
                default="00:00", max_length=10, verbose_name="winter peak start"
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="winter_rb",
            field=models.FloatField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="winter rb",
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="winter_sx",
            field=models.FloatField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="winter sx",
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="winter_zero_cost",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="winter zero cost"
            ),
        ),
        migrations.AddField(
            model_name="useranalysis",
            name="error_log",
            field=models.TextField(default=1, verbose_name="error log"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="useranalysis",
            name="user_name",
            field=models.CharField(default="", max_length=50, verbose_name="user name"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="vehiclecategorymodel",
            name="base_electricity_tariff",
            field=models.FloatField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="base electricity tariff",
            ),
        ),
        migrations.AddField(
            model_name="vehiclecategorymodel",
            name="cost_per_unit",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="cost per unit"
            ),
        ),
        migrations.AddField(
            model_name="vehiclecategorymodel",
            name="energy_consumption",
            field=models.FloatField(
                blank=True, default=0.0, null=True, verbose_name="energy consumption"
            ),
        ),
        migrations.AddField(
            model_name="vehiclecategorymodel",
            name="fuel_efficiency",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="fuel efficiency"
            ),
        ),
        migrations.AddField(
            model_name="vehiclecategorymodel",
            name="growth_rate",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="growth rate"
            ),
        ),
        migrations.AddField(
            model_name="vehiclecategorymodel",
            name="handling_cost",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="handling cost"
            ),
        ),
        migrations.AddField(
            model_name="vehiclecategorymodel",
            name="kwh_capacity",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="kWh capacity"
            ),
        ),
        migrations.AddField(
            model_name="vehiclecategorymodel",
            name="lifespan_years",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="lifespan (years)"
            ),
        ),
        migrations.AddField(
            model_name="vehiclecategorymodel",
            name="penetration_rate",
            field=models.FloatField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="penetration rate",
            ),
        ),
        migrations.AddField(
            model_name="vehiclecategorymodel",
            name="range_km",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="range (km)"
            ),
        ),
        migrations.AddField(
            model_name="vehiclecategorymodel",
            name="row_limit_xl",
            field=models.PositiveIntegerField(
                default=2000000, verbose_name="row limit (Excel)"
            ),
        ),
        migrations.AddField(
            model_name="vehiclecategorymodel",
            name="subsidy_amount",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="subsidy amount"
            ),
        ),
        migrations.AddField(
            model_name="vehiclecategorymodel",
            name="usage_factor",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="usage factor"
            ),
        ),
        migrations.AddField(
            model_name="vehiclecategorymodel",
            name="vehicle_category",
            field=models.CharField(
                choices=[
                    ("car", "Car"),
                    ("bus", "Bus"),
                    ("2-wheeler", "2-Wheeler"),
                    ("3-wheeler", "3-Wheeler"),
                    ("others", "Others"),
                ],
                default="",
                max_length=20,
                verbose_name="vehicle category",
            ),
        ),
        migrations.AddField(
            model_name="vehiclecategorymodel",
            name="vehicle_count",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="vehicle count"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="category_data",
            field=models.JSONField(default=list, verbose_name="category data"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="date1_end",
            field=models.CharField(
                default="", max_length=10, verbose_name="date 1 end"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="date1_start",
            field=models.CharField(
                default="", max_length=10, verbose_name="date 1 start"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="date2_end",
            field=models.CharField(
                default="", max_length=10, verbose_name="date 2 end"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="date2_start",
            field=models.CharField(
                default="", max_length=10, verbose_name="date 2 start"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="name",
            field=models.CharField(max_length=255, verbose_name="analysis name"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="resolution",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="resolution",
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="shared_saving",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="shared saving"
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="summer_date",
            field=models.JSONField(default=list, verbose_name="summer date"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_analyses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="user_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                null=True,
                verbose_name="user name",
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="vehicle_category_data",
            field=models.JSONField(default=list, verbose_name="vehicle category data"),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="winter_date",
            field=models.JSONField(default=list, verbose_name="winter date"),
        ),
        migrations.AlterField(
            model_name="files",
            name="file",
            field=models.FileField(upload_to="file_upload/", verbose_name="file"),
        ),
        migrations.AlterField(
            model_name="loadcategorymodel",
            name="category",
            field=models.CharField(
                choices=[
                    ("commercial", "Commercial"),
                    ("agricultural", "Agricultural"),
                    ("industrial", "Industrial"),
                    ("residential", "Residential"),
                    ("public", "Public"),
                    ("others", "Others"),
                ],
                default="",
                max_length=20,
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="permanentanalysis",
            name="category_data",
            field=models.JSONField(default=list, verbose_name="category data"),
        ),
        migrations.AlterField(
            model_name="permanentanalysis",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="permanentanalysis",
            name="date1_end",
            field=models.CharField(
                default="", max_length=10, verbose_name="date 1 end"
            ),
        ),
        migrations.AlterField(
            model_name="permanentanalysis",
            name="date1_start",
            field=models.CharField(
                default="", max_length=10, verbose_name="date 1 start"
            ),
        ),
        migrations.AlterField(
            model_name="permanentanalysis",
            name="date2_end",
            field=models.CharField(
                default="", max_length=10, verbose_name="date 2 end"
            ),
        ),
        migrations.AlterField(
            model_name="permanentanalysis",
            name="date2_start",
            field=models.CharField(
                default="", max_length=10, verbose_name="date 2 start"
            ),
        ),
        migrations.AlterField(
            model_name="permanentanalysis",
            name="name",
            field=models.CharField(max_length=255, verbose_name="analysis name"),
        ),
        migrations.AlterField(
            model_name="permanentanalysis",
            name="resolution",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="resolution",
            ),
        ),
        migrations.AlterField(
            model_name="permanentanalysis",
            name="shared_saving",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="shared saving"
            ),
        ),
        migrations.AlterField(
            model_name="permanentanalysis",
            name="summer_date",
            field=models.JSONField(default=list, verbose_name="summer date"),
        ),
        migrations.AlterField(
            model_name="permanentanalysis",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_analyses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="permanentanalysis",
            name="user_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                null=True,
                verbose_name="user name",
            ),
        ),
        migrations.AlterField(
            model_name="permanentanalysis",
            name="vehicle_category_data",
            field=models.JSONField(default=list, verbose_name="vehicle category data"),
        ),
        migrations.AlterField(
            model_name="permanentanalysis",
            name="winter_date",
            field=models.JSONField(default=list, verbose_name="winter date"),
        ),
        migrations.AlterField(
            model_name="useranalysis",
            name="status",
            field=models.CharField(
                blank=True, default="", max_length=20, null=True, verbose_name="status"
            ),
        ),
        migrations.AlterField(
            model_name="useranalysis",
            name="time",
            field=models.FloatField(
                blank=True, default=0.0, null=True, verbose_name="time"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="invitation_status",
            field=models.CharField(
                default="Pending", max_length=50, verbose_name="invitation status"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="invitation_token",
            field=models.CharField(
                blank=True, max_length=255, unique=True, verbose_name="invitation token"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="invitation_username",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="invitation username"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="organization",
            field=models.CharField(
                default="Not assigned", max_length=255, verbose_name="organization"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="password_reset_token",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="password reset token",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(default="user", max_length=50, verbose_name="role"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="temporary_password",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="temporary password"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="br_f",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="BR F"
            ),
        ),
        migrations.AddField(
            model_name="permanentanalysis",
            name="br_f",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="BR F"
            ),
        ),
        migrations.AddField(
            model_name="vehiclecategorymodel",
            name="cagr_v",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="CAGR (vehicles)"
            ),
        ),
    ]
