# Generated by Django 5.2.3 on 2025-07-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevate", "0009_files_created_at_files_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="is_load_split_file",
            field=models.CharField(
                blank=True,
                default="",
                max_length=400,
                null=True,
                verbose_name="load split file",
            ),
        ),
    ]
