# Generated by Django 5.2.3 on 2025-06-24 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="invitation_status",
            field=models.CharField(default="Pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="invitation_token",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="invitation_username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="organization",
            field=models.CharField(default="Not assigned", max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="temporary_password",
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
