# Generated by Django 5.2.3 on 2025-06-24 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_userprofile_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
