# Generated by Django 5.2.3 on 2025-06-27 05:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_alter_userprofile_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "dateCreated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("load_category", models.IntegerField()),
                ("is_load_split", models.CharField(max_length=10)),
                ("is_load_split_file", models.CharField(blank=True, max_length=255)),
                ("category_data", models.JSONField()),
                ("num_of_vehicle_category", models.IntegerField()),
                ("vehicle_category_data", models.JSONField()),
                ("resolution", models.IntegerField()),
                ("br_f", models.CharField(max_length=10)),
                ("shared_saving", models.IntegerField()),
                ("sum_pk_cost", models.FloatField()),
                ("sum_zero_cost", models.FloatField()),
                ("sum_op_cost", models.FloatField()),
                ("win_pk_cost", models.FloatField()),
                ("win_zero_cost", models.FloatField()),
                ("win_op_cost", models.FloatField()),
                ("summer_date", models.JSONField()),
                ("winter_date", models.JSONField()),
                ("s_pks", models.CharField(max_length=10)),
                ("s_pke", models.CharField(max_length=10)),
                ("s_sx", models.CharField(max_length=10)),
                ("s_ops", models.CharField(max_length=10)),
                ("s_ope", models.CharField(max_length=10)),
                ("s_rb", models.CharField(max_length=10)),
                ("w_pks", models.CharField(max_length=10)),
                ("w_pke", models.CharField(max_length=10)),
                ("w_sx", models.CharField(max_length=10)),
                ("w_ops", models.CharField(max_length=10)),
                ("w_ope", models.CharField(max_length=10)),
                ("w_rb", models.CharField(max_length=10)),
                ("date1_start", models.CharField(max_length=10)),
                ("date1_end", models.CharField(max_length=10)),
                ("date2_start", models.CharField(max_length=10)),
                ("date2_end", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
