# Generated by Django 3.0 on 2021-11-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersRegistration',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, primary_key=True, serialize=False, unique=True)),
                ('organizationTitle', models.CharField(max_length=100)),
            ],
        ),
    ]
