# Generated by Django 3.0 on 2021-11-15 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersregistration',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
