# Generated by Django 3.0 on 2021-11-17 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0002_usersregistration_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersRegistration',
        ),
    ]
