# Generated by Django 3.0 on 2021-11-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EVTools', '0003_delete_usersregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='evAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadCategory', models.IntegerField(default='', max_length=20)),
                ('isLoadSplit', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=4)),
                ('isLoadSplitFile', models.FileField(blank=True, default='', null=True, upload_to='LoadSplitFile')),
                ('commercial', models.IntegerField(blank=True, default='', null=True)),
                ('agriculture', models.IntegerField(blank=True, default='', null=True)),
                ('industrial', models.IntegerField(blank=True, default='', null=True)),
                ('residential', models.IntegerField(blank=True, default='', null=True)),
                ('public', models.IntegerField(blank=True, default='', null=True)),
                ('othes', models.IntegerField(blank=True, default='', null=True)),
                ('vahicalCategory', models.CharField(choices=[('Managed', 'Managed'), ('Unmanaged', 'Unmanaged')], default='', max_length=20)),
                ('isManagedFile', models.FileField(blank=True, default='', null=True, upload_to='ManagedFile')),
                ('senario', models.CharField(choices=[('0', 'Base + Ev'), ('1', 'Only EV')], default='', max_length=20)),
                ('isOverShot', models.CharField(choices=[('0', 'offshot to be spread over'), ('1', 'Per of total area to be spread over')], default='', max_length=20)),
                ('perOfTotalArea', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
