# Generated by Django 3.0 on 2021-11-18 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0004_evanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evanalysis',
            name='loadCategory',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='perOfTotalArea',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
