# Generated by Django 3.0 on 2021-11-18 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0006_auto_20211118_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evanalysis',
            name='perOfTotalArea',
            field=models.FloatField(blank=True, default='', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
