# Generated by Django 3.0 on 2021-11-18 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0007_auto_20211118_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='evanalysis',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
