# Generated by Django 3.0 on 2021-11-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0008_evanalysis_createdat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='evAnalysis',
        ),
    ]
