# Generated by Django 3.0 on 2021-11-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0010_evanalysis_loadcategorymodel_vehiclecategorymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evanalysis',
            name='module',
        ),
        migrations.RemoveField(
            model_name='evanalysis',
            name='moduleCategory',
        ),
        migrations.RemoveField(
            model_name='evanalysis',
            name='scenario',
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='tod',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='loadcategorymodel',
            name='specifySplit',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='isLoadSplitFile',
            field=models.FileField(blank=True, default='null', null=True, upload_to='LoadSplitFile'),
        ),
        migrations.AlterField(
            model_name='vehiclecategorymodel',
            name='vehicleCategory',
            field=models.CharField(choices=[('car', 'car'), ('bus', 'bus'), ('2-wheeler', '2-wheeler'), ('3-wheeler', '3-wheeler'), ('others', 'others')], default='', max_length=20),
        ),
    ]
