# Generated by Django 3.0 on 2021-11-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0011_auto_20211125_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evanalysis',
            name='isOverShot',
        ),
        migrations.RemoveField(
            model_name='evanalysis',
            name='perOfShotToBeSpread',
        ),
        migrations.RemoveField(
            model_name='evanalysis',
            name='perOfTotalArea',
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='isLoadSplit',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='', max_length=20),
        ),
    ]
