# Generated by Django 3.0 on 2021-11-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0013_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evanalysis',
            name='isLoadSplitFile',
            field=models.FileField(blank=True, default='null', null=True, upload_to='FileUpload/'),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='isManagedFile',
            field=models.FileField(blank=True, default='', null=True, upload_to='FileUpload/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='FileUpload/'),
        ),
        migrations.AlterField(
            model_name='loadcategorymodel',
            name='categoryFile',
            field=models.FileField(blank=True, default='', null=True, upload_to='FileUpload/'),
        ),
    ]
