# Generated by Django 3.0 on 2021-11-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0014_auto_20211126_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evanalysis',
            name='isLoadSplitFile',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='isManagedFile',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='loadcategorymodel',
            name='categoryFile',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
