# Generated by Django 3.0 on 2021-11-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0015_auto_20211126_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadcategorymodel',
            name='category',
            field=models.CharField(choices=[('commercial', 'commercial'), ('agricultural', 'agricultural'), ('industrial', 'industrial'), ('residential', 'residential'), ('public', 'public'), ('others', 'others')], default='', max_length=20),
        ),
    ]
