# Generated by Django 3.0 on 2021-11-30 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0017_auto_20211127_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evanalysis',
            old_name='tod',
            new_name='sharedSavaing',
        ),
        migrations.RemoveField(
            model_name='evanalysis',
            name='isManagedFile',
        ),
        migrations.RemoveField(
            model_name='loadcategorymodel',
            name='baseElectricity',
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='end_date',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='start_date',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='sum_op_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='sum_pk_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='sum_zero_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='win_op_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='win_pk_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='win_zero_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecategorymodel',
            name='baseElectricityTariff',
            field=models.FloatField(blank=True, default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
