# Generated by Django 3.0 on 2021-11-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0018_auto_20211130_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evanalysis',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='evanalysis',
            name='start_date',
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='date1_end',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='date1_start',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='date2_end',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='date2_start',
            field=models.CharField(default='', max_length=10),
        ),
    ]
