# Generated by Django 3.0 on 2021-12-01 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0019_auto_20211130_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evanalysis',
            name='win_zero_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loadcategorymodel',
            name='salesCAGR',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='loadcategorymodel',
            name='specifySplit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecategorymodel',
            name='p',
            field=models.FloatField(blank=True, default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
