# Generated by Django 3.0 on 2021-12-02 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0020_auto_20211201_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='evanalysis',
            name='s_ope',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='s_ops',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='s_pke',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='s_pks',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='s_rb',
            field=models.FloatField(blank=True, default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='s_sx',
            field=models.FloatField(blank=True, default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='w_ope',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='w_ops',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='w_pke',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='w_pks',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='w_rb',
            field=models.FloatField(blank=True, default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='evanalysis',
            name='w_sx',
            field=models.FloatField(blank=True, default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
