# Generated by Django 3.0 on 2021-12-02 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0021_auto_20211202_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evanalysis',
            name='s_rb',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='s_sx',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='w_ope',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='w_ops',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='w_pke',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='w_pks',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='w_rb',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='w_sx',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='vehiclecategorymodel',
            name='baseElectricityTariff',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='vehiclecategorymodel',
            name='p',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
