# Generated by Django 3.0 on 2021-12-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0023_auto_20211203_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='evanalysis',
            name='fileId',
            field=models.IntegerField(default=0),
        ),
    ]
