# Generated by Django 3.0 on 2021-12-07 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0025_auto_20211207_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evanalysis',
            name='loadCategory1',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_Cat_1', to='EVTools.LoadCategoryModel'),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='loadCategory2',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_Cat_2', to='EVTools.LoadCategoryModel'),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='loadCategory4',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_Cat_4', to='EVTools.LoadCategoryModel'),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='loadCategory5',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_Cat_5', to='EVTools.LoadCategoryModel'),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='loadCategory6',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_Cat_6', to='EVTools.LoadCategoryModel'),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='vehicleCategoryData1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_Cat_1', to='EVTools.vehicleCategoryModel'),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='vehicleCategoryData2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_Cat_2', to='EVTools.vehicleCategoryModel'),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='vehicleCategoryData3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_Cat_3', to='EVTools.vehicleCategoryModel'),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='vehicleCategoryData4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_Cat_4', to='EVTools.vehicleCategoryModel'),
        ),
        migrations.AlterField(
            model_name='evanalysis',
            name='vehicleCategoryData5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_Cat_5', to='EVTools.vehicleCategoryModel'),
        ),
    ]
