# Generated by Django 3.0 on 2022-01-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0026_auto_20211207_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='userAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='', max_length=50)),
                ('status', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('errorLog', models.TextField()),
                ('time', models.TimeField(blank=True)),
            ],
        ),
    ]
