# Generated by Django 3.0 on 2022-01-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0027_useranalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='evanalysis',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
