# Generated by Django 3.0 on 2022-01-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVTools', '0028_evanalysis_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranalysis',
            name='time',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
