# Generated by Django 5.2 on 2025-04-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EVTools", "0029_auto_20220106_1003"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evanalysis",
            options={"verbose_name_plural": "Ev Analysis's"},
        ),
        migrations.AlterModelOptions(
            name="useranalysis",
            options={"verbose_name_plural": "User Analysis's Log"},
        ),
        migrations.AlterField(
            model_name="vehiclecategorymodel",
            name="f",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
