# Generated by Django 5.2 on 2025-05-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EVTools", "0031_alter_evanalysis_sum_op_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evanalysis",
            name="sum_op_cost",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="evanalysis",
            name="sum_pk_cost",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="evanalysis",
            name="sum_zero_cost",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="evanalysis",
            name="win_op_cost",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="evanalysis",
            name="win_pk_cost",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="vehiclecategorymodel",
            name="f",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
