# Generated by Django 5.2.3 on 2025-07-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_self_registered",
            field=models.BooleanField(default=False, verbose_name="is self registered"),
        ),
    ]
