# Generated by Django 5.2.5 on 2025-08-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevate", "0002_userprofile_is_self_registered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="invitation_token",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="invitation token",
            ),
        ),
    ]
