# Generated by Django 5.2.5 on 2025-09-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elevate", "0003_alter_userprofile_invitation_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="designation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="intended_use",
            field=models.TextField(blank=True, null=True),
        ),
    ]
